mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name = 'home')
]
   

polls/urls.py
from django.urls import path
from . import views 

app_name = 'polls'
urlpatterns = [
    path('', views.index, name ='index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('<int:question_id>/results/', views.results, name = 'results'),
    path('<int:question_id>/vote/', views.vote, name ='vote'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
    path('add_question/', views.add_question, name = 'add_question' ),
    path('save_poll/', views.save_poll, name='save_poll'),
    path('questions/', views.QuestionList.as_view()),
]
    

polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published', default = timezone.now)
    user_id = models.IntegerField(default = 0)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name = 'choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
        

polls/forms.py
from django import forms



class PollForm(forms.Form):
    question = forms.CharField(label ='Your question',)
    choice_1= forms.CharField(label ='Your first choice')
    choice_2= forms.CharField(label ='Your second choice')
    choice_3= forms.CharField(label ='Your third choice')

   

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse, reverse_lazy
from .models import Question, Choice
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import PollForm
from django.utils import timezone
from .serializers import QuestionSerializer
from rest_framework import generics


@login_required
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list, }

    return render(request, 'polls/index.html', context)


@login_required
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    current_user = request.user.id

    if current_user == question.user_id:
        return render(request, 'polls/error_response.html')
    else:
        return render(request, 'polls/detail.html', {'question': question})


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {'question': question, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


@login_required
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


@login_required
def add_question(request):
 
    if request.method == 'POST':
        form = PollForm(request.POST)

        if form.is_valid():
            save_poll(request)
            return HttpResponseRedirect(reverse("polls:index"))

    else:
        form = PollForm()

    return render(request, 'polls/add_question.html', {'form': form})


@login_required
def save_poll(request):
    
    newQuestion = Question(question_text=request.POST['question'], pub_date=timezone.now(), user_id=request.user.id)

    newQuestion.save()

    newQuestion.choices.create(choice_text=request.POST['choice_1'], votes=0)
    newQuestion.choices.create(choice_text=request.POST['choice_2'], votes=0)
    newQuestion.choices.create(choice_text=request.POST['choice_3'], votes=0)

    return HttpResponseRedirect(reverse("polls:index"))


class QuestionList(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class QuestionDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

polls/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}The Django Poll App{% endblock %}</title>
      </head>
      <body>
        <main>
          {% block content %}
          {% endblock %}
        </main>
      </body>  
</html>

polls/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{user.username}} 
<br/>
<br/>

<a href = "{%url 'polls:index' %}">Go to the polls</a>

<p><a href = "{%url 'logout' %}"> Logout </p>

{% else %}
<p>You are not logged in</p>
<a href = "{%url 'login' %}">Login</a>

<br/>
<p>New user?</p>
<a href = "{% url 'polls:signup' %}">Sign up here</a>

{% endif %}


{% endblock %}

polls/templates/polls/add_question.html
<h1>Add a poll</h1>


 <form id = "question_form" method = "POST" action="{% url 'polls:add_question' %}">
    {% csrf_token %}

    <table>
        {{ form }}
       
    </table>

    <input type ="submit" name ="submit" value = "Create Question" />
</form> 

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}">

<h1 id="question">{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choices.all %}
<div id ="choices">
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
</div>
{% endfor %}
<input id="button" type="submit" value="Vote">
</form>

polls/templates/polls/error_response.html
<div>
<h2>You cannot answer a poll you created</h2>
<br/>
<a href = "{%url 'polls:index' %}">Go back to the polls</a>
</div>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/poll_templates.css' %}">


<a id ="home" href = "{%url 'home' %}">Home</a>

{% if latest_question_list%}
<h1 id="title">Latest Polls</h1>
<ol>
    {%for question in latest_question_list%}
    <li><a class="links" href = "{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
    {%endfor%}
</ol>
{%else%}
<p> No polls are available.</p>
{% endif %}





<button> <a id="add-poll" href = "{% url 'polls:add_question' %}">Add a new poll</a></button>

polls/templates/polls/results.html
<h1> {{question.question_text}}</h1>

<ul>
    {%for choice in question.choices.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
    </li>
    {%endfor%}
</ul>

<a href = "{%url 'polls:detail' question.id %}" > Vote again? </a>
<br><br>
<a href = "{%url 'polls:index' %}">Back to polls</a>

polls/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}